name: tree_scanner
description: A Flutter app for tree scanning.

# Add SDK constraints
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # All Flutter Packages
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # --- Splash Screen ----
  flutter_native_splash: ^2.3.1

  # Get packages
  get: ^4.6.6
  get_storage: ^2.1.1

  http: ^1.2.2

  # Other Package
  connectivity_plus: ^5.0.2
  shimmer: ^3.0.0

  # For picking images
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  lottie: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6
  google_fonts: ^6.1.0

   # ----- FireBase -------------
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add any other dev dependencies here if needed

flutter:
  uses-material-design: true



  assets:
    - assets/images/content/
    - assets/images/banners/
    - assets/logos/
    - assets/
    - assets/images/reviews/
    - assets/images/products/
    - assets/animations/
    - assets/images/on_boarding/
